### ISSUE TITLE
Cannot Add User to Multiple OPs on Event

### ISSUE THREAD

**Issue by MikeDacre** [andyl/BAMRU-Org#14]
When trying to add a member to multiple operational periods for a single event on Google Chrome for Linux  45.0.2454.85 (64-bit), only the first operational period is available for adding members. The others are links to 'Add Participant' that point to the current URL with a hash on the end (JavaScript links I think), when I click these, nothing happens. See screenshot below. This issue is reproducible on Firefox 40.0.3-1, also on Linux, and also the latest Chrome for Android (I have no idea how to get versions on Android). I have not tested on any other platforms.

![311628c4-6372-11e5-8317-f2899a73abf7](https://cloud.githubusercontent.com/assets/77714/10108016/6ded823c-6373-11e5-9de0-c00a60d225da.png)

**Comment by andyl** [comment]
Fixed this awhile ago on BAMRU.net
